name: challenge_moteis_go
description: "A application for Guia de Moteis Go test"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  http: ^1.3.0
  get_it: ^8.0.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7




flutter:

  
  uses-material-design: true

  
  fonts:
    - family: Cairo
      fonts:
      - asset: assets/fonts/CairoFont.ttf
  
